const menu = [
  {
    id: 1,
    title: 'garlic pork belly',
    category: 'pork',
    price: 'blowjob',
    img: './images/garlicporkbelly.jpg',
    desc: `pork belly marinated in garlic, pear, onion and soy `,
  },
  {
    id: 2,
    title: 'spicy pork belly',
    category: 'pork',
    price: 'blowjob',
    img: './images/spicyporkbelly.jpg',
    desc: `pork belly marinated in gochujang, sesame oil, red chile oil, and brown sugar `,
  },
  {
    id: 3,
    title: 'soy pork belly',
    category: 'pork',
    price:'blowjob',
    img: './images/soyporkbelly.jpg',
    desc: `pork belly marinated in soy, brown sugar, garlic, onion, sesame oil and honey`,
  },
  {
    id: 4,
    title: 'beef bulgogi',
    category: 'beef',
    price: 'blowjob',
    img: './images/beefbulgogi.jpg',
    desc: `ribeye sliced thin and marinated in pear, brown sugar, soy, sesame oil, onion and garlic `,
  },
  {
    id: 5,
    title: 'hawaiian bulgogi',
    category: 'beef',
    price: 'two blowjob',
    img: './images/hawaiianbulgogi.jpg',
    desc: `beef bulgogi, but with pineapples `,
  },
  {
    id: 6,
    title: 'shrimp',
    category: 'seafood',
    price: 18.99,
    img: './images/shrimp.jpg',
    desc: `Fresh caught pacific shrimp from Savannah, Georgia`,
  },
  {
    id: 7,
    title: 'kimchi',
    category: 'spread',
    price: 'free',
    img: './images/kimchi.jpg',
    desc: `marinated napa cabbage with raddish, carrot, onion`,
  },
];
export default menu;
